## A Heat environment file which can be used to set up storage
## backends. Defaults to Ceph used as a backend for Cinder, Glance and
## Nova ephemeral storage.
resource_registry:
  OS::TripleO::Services::CephMon: /usr/share/openstack-tripleo-heat-templates/puppet/services/ceph-mon.yaml
  OS::TripleO::Services::CephOSD: /usr/share/openstack-tripleo-heat-templates/puppet/services/ceph-osd.yaml
  OS::TripleO::Services::CephClient: /usr/share/openstack-tripleo-heat-templates/puppet/services/ceph-client.yaml

parameter_defaults:
  CinderEnableIscsiBackend: false
  CinderEnableRbdBackend: true
  CinderBackupBackend: ceph
  NovaEnableRbdBackend: true
  GlanceBackend: rbd
  GnocchiBackend: rbd

  ExtraConfig:
    ceph::profile::params::osds:
     '/dev/vda':
       journal:
     '/dev/vdb':
       journal: 
     '/dev/vdc':
       journal:
     '/dev/vdd':
       journal:
     '/dev/vde':
       journal:
     '/dev/vdf':
       journal:
     '/dev/vdg':
       journal:
     '/dev/vdh':
       journal:
     '/dev/vdi':
       journal:
     '/dev/vdj':
       journal:

    ceph::profile::params::osd_max_object_name_len: 256
    ceph::profile::params::osd_max_object_namespace_len: 64
    ceph::profile::params::osd_pool_default_pg_num: 128
    ceph::profile::params::osd_pool_default_pgp_num: 128
    ceph::profile::params::osd_pool_default_size: 3
    ceph::profile::params::osd_pool_default_min_size: 2
    ceph::profile::params::osd_recovery_op_priority: 2
  OsdComputeExtraConfig:
    ceph::profile::params::osd_journal_size: 5120
